CREATE TABLE posts (
	id 					int 				primary key GENERATED by default AS identity,
	title				varchar(100)		not null,
	author_name			varchar(10) 		NOT NULL,
	total_views			int					not null default 0,
	content				text 				not null,
	is_active			boolean				not null default true,
	password 			varchar(64)			not null,
	created_at 			TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP not null,
	updated_at			TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP not null
);

CREATE INDEX posts_created_at_idx ON posts USING btree (created_at);

-- Optional
insert into posts(title, author_name, "content", password)
values
('美, SK하이닉스 6600억 보조금 확정… “인디애나 공장 세워 공급망 확대 기대”', '박현익 기자', 'SK하이닉스가 미국 인디애나주에 짓는 반도체 공장에 대한 6600억 원 규모의 미 정부 보조금이 최종 확정됐다. 도널드 트럼프 정부 2기 출범 전 조 바이든 행정부에서 보조금 지급을 매듭지으며 불확실성이 해소됐다는 평가가 나온다.

미 상무부는 19일(현지 시간) “바이든-해리스 행정부는 SK하이닉스에 ‘칩스(CHIPS) 인센티브 프로그램’에 따라 4억5800만 달러(약 6600억 원)의 직접 보조금을 지급한다”고 발표했다. 미 정부가 칩스법(반도체 지원법)에 따른 보조금 지급 최종 계약을 체결한 것이다. 앞서 예비적 각서(PMT)에서 잠정 합의했던 4억5000만 달러보다 800만 달러 증액한 규모다. 공장 및 관련 부대시설 설립에 드는 비용 등을 고려해 지원 규모를 확대한 것으로 전해졌다. 상무부는 또 직접 보조금 외에도 최대 5억 달러 규모의 대출을 지원할 예정이라고 밝혔다.

지나 러몬도 미 상무장관은 “글로벌 고대역폭메모리(HBM) 생산업체인 SK하이닉스의 투자로 미국은 AI 공급망을 강화하고 인디애나주에 새로운 일자리를 창출할 것”이라고 했다. 곽노정 SK하이닉스 사장은 “미 정부, 인디애나주, 퍼듀대, 미국 사업 파트너들과 협력해 강력한 AI 반도체 공급망을 구축하기를 기대한다”고 밝혔다.', '$2a$10$p9aQVkoRqexvj.uoLyK2e.gYFiFPHGQHF7UnTiIOQHoC4imgAYmEu'),
('Trump meets with TikTok CEO at Mar-a-Lago as company asks', 'Devan Cole', 'President-elect Donald Trump met with the head of TikTok at his Mar-a-Lago club Monday afternoon, a person familiar with the meeting told CNN, as the social media giant is asking the Supreme Court to wade into a court fight over use of the app in the United States.

The pre-scheduled meeting with TikTok CEO Shou Chew is believed to be the first time the men have met since Trump’s electoral victory in November, another person told CNN. Chew, who was seen at Trump’s Florida resort in early December, has been trying to meet with Trump since he was elected, and is just the latest meeting the president-elect is holding with top executives from some of America’s largest tech companies.', '$2a$10$p9aQVkoRqexvj.uoLyK2e.gYFiFPHGQHF7UnTiIOQHoC4imgAYmEu');

